### ISSUE TITLE
Feature: Terms of Service Screen

### ISSUE THREAD

**Issue by mgacrama211176** [mgacrama211176/katiwala#18]
Need to add Terms of Service Screen

![Image](https://github.com/mgacrama211176/katiwala/assets/81429150/9246e26f-3d92-466e-88ce-df5e8cd2cef8)

**Comment by stolenfallen1** [comment]
Also this one hihi, if it's okay or we can co-author the same PR if you guys want @mgacrama211176 @marlonosia
