### ISSUE TITLE
Feature: Privacy Policy Screen

### ISSUE THREAD

**Issue by mgacrama211176** [mgacrama211176/katiwala#19]
Need to add Privacy Policy screen before completing the registration Process.

![Image](https://github.com/mgacrama211176/katiwala/assets/81429150/aeec2be9-1ee4-48e6-8e32-a9c0215022e9)

**Comment by stolenfallen1** [comment]
Can I do this one for fun bro @mgacrama211176 @marlonosia ?

I'll add comments to the code too haha, I don't have a side project idea na kasi lol HAHAHAHA

**Comment by mgacrama211176** [comment]
Go bro
