### ISSUE TITLE
Bug: DOB UI BUG

### ISSUE THREAD

**Issue by mgacrama211176** [mgacrama211176/katiwala#22]
Date of birth bug when pressed. The UI at the back changes it height.

![420939829_6980869428699025_2698012192403844604_n](https://github.com/mgacrama211176/katiwala/assets/81429150/24f4f4b5-8e0e-49f1-9f53-ac77856b10c1)
![421135030_734968401931310_6663754620321155415_n](https://github.com/mgacrama211176/katiwala/assets/81429150/b0ee3de9-9934-4274-94dc-1f8092a8a1b2)

**Comment by marlonosia** [comment]
done fix the height of container

**Comment by mgacrama211176** [comment]
Please add a PR for checking

**Comment by mgacrama211176** [comment]
> done fix the height of container

Please create a pull request for checking
