### ISSUE TITLE
Bug: password indicator 

### ISSUE THREAD

**Issue by marlonosia** [mgacrama211176/katiwala#26]
indicator error for password did not match boolean true or false if the password is correct the system read correct but if not the system responds password did not match 
![426724379_1669819733825188_8611412542821171263_n](https://github.com/mgacrama211176/katiwala/assets/146900897/bd38e093-35d3-4a51-a68e-065d2499ea0b)

**Comment by mgacrama211176** [comment]
Issue Resolved and merged to main.

Issue closed.
